version: '3'
services:
  mg-php5.6:
    image: b00dfefcfa7a
    restart: always
  
    volumes:
      - "/home/greg/docker-php5.6/tmp:/tmp"
      - "/home/greg/docker-php5.6/cli/ini.php:/etc/php/5.6/cli/ini.php"
  
    tty: true